name: Build Executable all

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - macos-15-large

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile spread_viz.py --collect-all dash_cytoscape --collect-all dash_iconify --collect-all dash_bootstrap_templates --collect-all wiw_app --hidden-import=dash.backends._flask

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpreadViz-${{ runner.os }}-${{ runner.arch }}
          path: |
            dist/spread_viz
            dist/spread_viz.exe