name: Build Dash Executable

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - macos-15-large

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile spread_viz.py --collect-all dash_cytoscape --collect-all dash_iconify --collect-all dash_bootstrap_templates --collect-all wiw_app

      - name: Zip the executable
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            pwsh -Command "Compress-Archive -Path dist\spread_viz -DestinationPath dist\SpreadViz-Windows-${{ runner.arch }}.zip"
          else
            cd dist
            zip SpreadViz-${{ runner.os }}-${{ runner.arch }}.zip spread_viz
          fi
          
      - name: Get latest release tag
        id: get_latest
        run: |
          TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SpreadViz-${{ runner.os }}-${{ runner.arch }}.zip
          tag_name: ${{ steps.get_latest.outputs.tag }}
